export const users = [
    {
        id: 1,
        username: 'john_doe',
        email: 'john.doe@example.com',
        phone: '123-456-7890',
        website: 'www.johndoe.com',
    },
    {
        id: 2,
        username: 'jane_smith',
        email: 'jane.smith@example.com',
        phone: '987-654-3210',
        website: 'www.janesmith.com',
    },
    {
        id: 3,
        username: 'mike_johnson',
        email: 'mike.johnson@example.com',
        phone: '555-123-4567',
        website: 'www.mikejohnson.com',
    },
    {
        id: 4,
        username: 'sarah_adams',
        email: 'sarah.adams@example.com',
        phone: '111-222-3333',
        website: 'www.sarahadams.com',
    },
    {
        id: 5,
        username: 'robert_wilson',
        email: 'robert.wilson@example.com',
        phone: '999-888-7777',
        website: 'www.robertwilson.com',
    },
    {
        id: 6,
        username: 'linda_jackson',
        email: 'linda.jackson@example.com',
        phone: '444-555-6666',
        website: 'www.lindajackson.com',
    },
    {
        id: 7,
        username: 'samuel_smith',
        email: 'samuel.smith@example.com',
        phone: '777-666-5555',
        website: 'www.samuelsmith.com',
    },
    {
        id: 8,
        username: 'emily_davis',
        email: 'emily.davis@example.com',
        phone: '222-333-4444',
        website: 'www.emilydavis.com',
    },
    {
        id: 9,
        username: 'david_miller',
        email: 'david.miller@example.com',
        phone: '888-777-6666',
        website: 'www.davidmiller.com',
    },
    {
        id: 10,
        username: 'jennifer_thomas',
        email: 'jennifer.thomas@example.com',
        phone: '333-444-5555',
        website: 'www.jenniferthomas.com',
    },
];
